site_name: Shuichiro Shimizu
theme:
  name: material
nav:
    - Home: index.md
    - Education: education.md
    - Publications: publications.md
    - Experiences: experiences.md
    - Awards and Grants: awards_and_grants.md
